version: 2
general:
  branches:
    only:
      - master
      - chore/enable-circleci
jobs:
  deploy:
    docker:
      - image: circleci/node:8-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run:
          name: Install awscli
          command: |
            sudo pip install awscli
            aws --version
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Deploy using CodeDeploy
          command: bash infrastructure/codedeploy.sh
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
workflows:
  version: 2
  deploy:
    jobs:
    - deploy
